<?php $this->headLink()->appendStylesheet('/styles/index/styles.css'); ?>
<?php $this->headScript()->appendFile('/scripts/index/scripts.js'); ?>
<section id="intro-wrapper" class="container">
	<ul id="intro-content" class="row">
		<li id="intro-line-one" class="onecol">
			Hi.
		</li>
		<li id="intro-line-two" class="twelvecol">
			My name is Ken Stowell,
		</li>
		<li id="intro-line-three" class="eightcol">
			and I thrive on creating beautiful
		</li>
		<li id="intro-line-four" class="sixcol last">
			experiences for the web.
		</li>
	</ul>
</section>
<footer id="intro-footer">

</footer>