<?php $this->headLink()->appendStylesheet('/styles/services/styles.css'); ?>
<?php $this->headScript()->appendFile('/scripts/services/scripts.js'); ?>
<section id="services-wrapper" class="container">
	<img src="../../images/services/services_bg.png" alt="bg" id="services_bg" />
	<header id="services-header">
		<div id="logo">
			<img src="../../images/general/logo.png" alt="ken stowell: visual developer" />
		</div>
		<nav id="services-nav" class="row">
			<a href="/about">about</a>
			<a href="/services" class="current-services">services</a>
			<a href="/work">work</a>
			<a href="/contact">contact</a>
		</nav>
	</header>
	<section id="services-content" class="row">
		<header class="twocol">What I do:</header>

		<article>
			<ul id="services-list" class="row">
				<li id="development" class="service-item fourcol">
					<span class="dev-title">Development</span>
					<p>
						I pride myself in offering exceptional
						web programming. I’m Passionate
						towards object oreinted architecture
						and implementing intelligent design
						patterns.
					</p>
					<div id="development-content" class="service-details" style="display:none;">
						<p>
							I pride myself in offering exceptional web programming. I’m Passionate
							towards object oreinted architecture and implementing intelligent design
							patterns.
						</p>
						<h4>The Service:</h4>
						<p>
							PHP(5), MySQL, Zend Framework, Code Igniter, JavaScript, jQuery, HTML(5), CSS(3).
							Pretty much everything you’d expect from a web developer.
						</p>
						<h4>The Cost:</h4>
						<p>
							I don’t believe in flat rates or concrete pricing structures. Whether you operate a small service from your home or are
							running a large business, I take everything into consideration. At the end of the day what I beleive in is being reasonable.
						</p>
						<h4>The Project:</h4>
						<p>
							If you’re interested in contacting me for a bid or proposal, feel free todo so <a href="/contact">here</a>.
						</p>
					</div>
				</li>
				<li id="design" class="service-item fourcol">
						<span class="design-title">Design</span>
						<p>Writing intelligent code is one thing,
						but designing how that code
						meets the user is the real reason I
						am obsessed with the web.</p>
					<div id="design-content" class="service-details" style="display:none;">
						<p>
							Writing intelligent code is one thing, but designing how that code meets the user is the real reason I am obsessed with the web.
						</p>
						<h4>The Service:</h4>
						<p>
							UI/UX design and planning. If you’re interested in obtaining commerical graphics and/or logo design - I’m probably not
							your man.
						</p>
						<h4>The Cost:</h4>
						<p>
							I don’t believe in flat rates or concrete pricing structures. Whether you operate a small service from your home or are
							running a large business, I take everything into consideration. At the end of the day what I beleive in is being reasonable.
						</p>
						<h4>The Project:</h4>
						<p>
							If you’re interested in contacting me for a bid or proposal, feel free todo so <a href="/contact">here</a>.
						</p>
					</div>
				</li>
				<li id="consulting" class="service-item fourcol last">
						<span class="consulting-title">Consulting</span>
						<p>Have all the resources and just
						need a plan? I can provide your
						team with technical insights
						that will bring your application
						speed and stability.</p>

					<div id="consulting-content" class="service-details" style="display:none;">
						<p>
							Have all the resources and just need a plan? I can provide your team with technical insights that will bring your application
							speed and stability.
						</p>
						<h4>The Service:</h4>
						<p>
							From wokflow and environments to actually writing the code - let’s talk about how to best build your application.
						</p>
						<h4>The Cost:</h4>
						<p>
							I don’t believe in flat rates or concrete pricing structures. Whether you operate a small service from your home or are
							running a large business, I take everything into consideration. At the end of the day what I beleive in is being reasonable.
						</p>
						<h4>The Project:</h4>
						<p>
							If you’re interested in contacting me for a bid or proposal, feel free todo so <a href="/contact">here</a>.
						</p>
					</div>
				</li>
			</ul>
		</article>
		<div id="blackout" style="display: none;"></div>
	</section>
	<footer id="services-footer">

	</footer>
</section>