<header>
	<h2>Blink Budget</h2>
	<img src="../../images/work/blink_budget_logo.png" alt="Blink Budget" class="work-details-image blink-budget" />
</header>

<section class="status">
	<header class="status-header">
		<h3>Project Status: <span class="status-value">in development</span></h3>
	</header>
</section>

<section class="description">
	<header class="description-header">
		<h3>Project Description</h3>
	</header>
	<article class="description-article">
		<p>
			There's a lot of financial management software out there. Blink Budget sets itself apart by its pure simplicity: sometimes you just want to know
			how much money from your paycheck you'll have left after bills and other expenses.
		</p>
		<p>
			In it's more advanced features, you can still get the power of the giants like Quicken or Mint.com - only with an interface that doesn't look like it
			was designed by an 8 year old ;) You'll have the ability to balance your register and upload reciepts which can automatically be added to your budget.
		</p>
	</article>
</section>

<section class="work-samples">
	<header class="work-samples-header">
		<h3>Work Samples</h3>
	</header>
	<article>
		<p>
			As this is still in development - there's not too much I can spill the beans on yet :) Needless to say I am very excited about this project!
		</p>
		<p><a href="http://www.blink-budget.com" target="_blank">Blink Budget</a></p>
	</article>
</section>