<header>
	<h2>Dev-Docs</h2>
	<img src="../../images/work/dev_docs_logo.png" alt="Dev-Docs" class="work-details-image" />
</header>

<section class="status">
	<header class="status-header">
		<h3>Project Status: <span class="status-value">in development</span></h3>
	</header>
</section>

<section class="description">
	<header class="description-header">
		<h3>Project Description</h3>
	</header>
	<article class="description-article">
		<p>Dev-Docs is an application geared to providing a sleek interface and thorough functionality to meet software development teams documentation needs. </p>
		<p>
			Any developer will tell you that there is no such thing as too much documentation. I have personally experienced being recruited to projects well beyond
			their kick-off and being shocked when I open files and not see a single line of comment. And if something as miniscule as commenting code isn't happening,
			you can bet that application wide documentation is lacking - if present at all. Dev-Docs aims to make it not only easy but appealing to document code.
		</p>
	</article>
</section>

<section class="work-samples">
	<header class="work-samples-header">
		<h3>Work Samples</h3>
	</header>
	<article>
		<p>
			As this is still in development - there's not too much I can spill the beans on yet :) Feel free to visit the landing page and sign up to receive updates, etc!
		</p>
		<p><a href="http://www.dev-docs.com" target="_blank">Dev-Docs</a></p>
	</article>
</section>