<?php $this->headLink()->appendStylesheet('/styles/work/hostbaby.css'); ?>
<header>
	<h2>HostBaby</h2>
	<img src="../../images/work/hostbaby_logo.png" alt="HostBaby" class="work-details-image" />
</header>

<section class="status">
	<header class="status-header">
		<h3>Project Status: <span class="status-value">full-time development</span></h3>
	</header>
</section>

<section class="description">
	<header class="description-header">
		<h3>Project Description</h3>
	</header>
	<article class="description-article">
		<p>HostBaby is a shared hosting platform that primarily targets CD Baby and Book Baby users that need websites to help promote their self-published works.</p>
		<p>
			It also provides a top-notch CMS (content-management-system, like Word Press or Drupal) to help users get a professional looking site up and running
			quickly and easily. Most of my development time involves building building and improving features for this CMS while staying on the cutting edge of
			emerging technologies.
		</p>
	</article>
</section>

<section class="work-samples">
	<header class="work-samples-header">
		<h3>Work Samples</h3>
	</header>
	<article>
		<p>
			As this is quite the full featured application, selecting which of those features to display here is a bit of a challenge. Recently, however, we completed a new
			filtering interface for our site themes. Before, all were displayed in an un-paginated, overwhelming list. Now you can filter - in real-time - by color,
			layout type and the level of customization. See the screen shots below and check out the video attention this feature got from our marketing department!
		</p>
		<img src="../../images/work/theme-filter.png" alt="Theme Filter" />
		<p>Or the video:</p>
		<iframe width="560" height="315" src="http://www.youtube.com/embed/Ye_XKpqKOD8" frameborder="0" allowfullscreen></iframe>
		<p>Soon after that, we began work on our new HTML5 audio player. We needed a more elegant and prformance friendly solution to our previous Flash player.</p>
		<p>We first provide the user a way to add the new player to their site pages:</p>
		<img src="../../images/work/widget-interface.png" alt="Widget Interface" />
		<p>Then we provide a sleek drag and drop interface to let users add tracks to their playlist:</p>
		<img src="../../images/work/playlist.png" alt="Playlist Interface" />
		<p>And finally the player!</p>
		<img src="../../images/work/player.png" alt="PLayer" />
		<p>There's a movie for this as well!</p>
		<iframe width="560" height="315" src="http://www.youtube.com/embed/FDJ9igns6qo" frameborder="0" allowfullscreen></iframe>
	</article>
</section>

