<header>
	<h2>Sunny Rose Photography</h2>
	<img src="../../images/work/sunny_rose.png" alt="Sunny Rose Photography" class="work-details-image" />
</header>

<section class="status">
	<header class="status-header">
		<h3>Project Status: <span class="status-value">in testing</span></h3>
	</header>
</section>

<section class="description">
	<header class="description-header">
		<h3>Project Description</h3>
	</header>
	<article class="description-article">
		<p>
			Website for a local photographer. I chose to feature this site because it demonstrates that I love to work for all spectrums of clients - from personal
			enthusiast and small business owner to large-scale corporations. I love being a gateway to helping others tap into the web.
		</p>
	</article>
</section>

<section class="work-samples">
	<header class="work-samples-header">
		<h3>Work Samples</h3>
	</header>
	<article>
		<p>
			This site is currently in a QA process and will be launched shortly! It has been fun and I can't wait for it to go live! I'll post some work samples here
			as soon as I can. There is a photo management feature that I am particularly proud of and will showcase it here soon!
		</p>
		<p><a href="http://www.sunnyrosephotography.com" target="_blank">Sunny Rose Photography</a></p>
	</article>
</section>